In [8]:
import torch

# 1. 创建一个tensor的不同方法

In [9]:
# 创建三个不用维度的tensor
# 直接手动输入
one_dim = torch.tensor([1,2,3]) # 一维时为向量
two_dim = torch.tensor([[1,2,3]]) # 二维时为矩阵
three_dim = torch.tensor([[[1,2,3]]]) # 三维及以上统称为tensor
one_dim, two_dim, three_dim

(tensor([1, 2, 3]), tensor([[1, 2, 3]]), tensor([[[1, 2, 3]]]))

In [12]:
# 依照给定shape生成
rand_tensor = torch.rand(1,1,3) # 数值为[0,1)的均匀分布
ones_tensor = torch.ones(1,1,3)
zeros_tensor = torch.zeros(1,1,3)

rand_tensor, ones_tensor, zeros_tensor

(tensor([[[0.1045, 0.1738, 0.3145]]]),
 tensor([[[1., 1., 1.]]]),
 tensor([[[0., 0., 0.]]]))

In [21]:
# 依照别的tensor生成
three_dim = torch.tensor([[[1.,2.,3.]]])

rand_tensor = torch.rand_like(three_dim)
ones_tensor = torch.ones_like(three_dim)

rand_tensor, ones_tensor

(tensor([[[0.0991, 0.8246, 0.7280]]]), tensor([[[1., 1., 1.]]]))

# 2. 查看创建好的tensor的相关信息

In [25]:
# Long型的运算
one_dim = torch.tensor([1,2,3])
x = torch.rand_like(one_dim)

RuntimeError: "check_uniform_bounds" not implemented for 'Long'

In [33]:
# 位于CPU和GPU的两tensor做运算
device = 'cuda:0' if torch.cuda.is_available() else 'cpu'
print(device)

x = torch.rand(2,2,device=device)
y = torch.rand(2,2)
x + y

cuda:0


RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

In [35]:
# 两个shape不同的tensor做运算
x = torch.rand(2,2)
y = torch.rand(3,3)
x + y

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1

In [38]:
# tensor重要的属性：dtype, device, shape
device = 'cuda:0' if torch.cuda.is_available() else 'cpu'
print(device)

x = torch.rand(2,2,device=device)
print(x.dtype)
print(x.device)
print(x.shape)

cuda:0
torch.float32
cuda:0
torch.Size([2, 2])


# 3. tensor的运算（https://pytorch.org/docs/stable/torch.html）

In [42]:
# indexing（索引）与slicing（切片）
tensor = torch.ones(4, 4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [43]:
# 堆叠tensor
tensor = torch.ones(2, 3)
tensor_cat = torch.cat([tensor, tensor, tensor], dim=1)
tensor_cat

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [46]:
# 两个tensor加减（维度相同）
x1 = torch.ones(3,3)
x2 = torch.ones(3,3)
x1 + x2

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [73]:
# 两个tensor加减（维度不同，属于特殊情况）
x1 = torch.ones(1,3)
x2 = torch.rand(3,3)
x1 + x2

tensor([[1.6713, 1.8358, 1.6111],
        [1.2606, 1.2345, 1.9117],
        [1.5950, 1.5873, 1.8082]])

In [51]:
# 两个tensor相乘（element-wise）
x1 = torch.ones(2, 3)
x2 = torch.rand(2, 3)

print(x2)
x1 * x2

tensor([[0.1146, 0.2641, 0.5962],
        [0.8288, 0.4856, 0.9001]])


tensor([[0.1146, 0.2641, 0.5962],
        [0.8288, 0.4856, 0.9001]])

In [64]:
# 两个tensor相乘（matrix multiplication）
x1 = torch.ones(2, 3)
x2 = torch.rand(2, 3)

print('x2: ', x2, '\n')
print(x1.t().matmul(x2))
print(x1.t() @ x2)

x2:  tensor([[0.4138, 0.8780, 0.7249],
        [0.6107, 0.6399, 0.9087]]) 

tensor([[1.0245, 1.5179, 1.6336],
        [1.0245, 1.5179, 1.6336],
        [1.0245, 1.5179, 1.6336]])
tensor([[1.0245, 1.5179, 1.6336],
        [1.0245, 1.5179, 1.6336],
        [1.0245, 1.5179, 1.6336]])
