In [1]:
import torch

# 1. 创建一个tensor的不同方法

In [2]:
# 创建三个不用维度的tensor
# 直接手动输入
one_dim = torch.tensor([1,2,3]) # 一维时为向量
two_dim = torch.tensor([[1,2,3]]) # 二维时为矩阵
three_dim = torch.tensor([[[1,2,3]]]) # 三维及以上统称为tensor
one_dim, two_dim, three_dim

(tensor([1, 2, 3]), tensor([[1, 2, 3]]), tensor([[[1, 2, 3]]]))

In [3]:
# 依照给定shape生成
rand_tensor = torch.rand(1,1,3) # 数值为[0,1)的均匀分布
ones_tensor = torch.ones(1,1,3)
zeros_tensor = torch.zeros(1,1,3)

rand_tensor, ones_tensor, zeros_tensor

(tensor([[[0.1170, 0.3186, 0.2398]]]),
 tensor([[[1., 1., 1.]]]),
 tensor([[[0., 0., 0.]]]))

In [4]:
# 依照别的tensor生成
three_dim = torch.tensor([[[1.,2.,3.]]])

rand_tensor = torch.rand_like(three_dim)
ones_tensor = torch.ones_like(three_dim)

rand_tensor, ones_tensor

(tensor([[[0.9788, 0.6083, 0.1664]]]), tensor([[[1., 1., 1.]]]))

# 2. 查看创建好的tensor的相关信息

In [7]:
# Long型的运算
one_dim = torch.tensor([1.,2.,3.])
x = torch.rand_like(one_dim)
x

tensor([0.7850, 0.4236, 0.2115])

In [9]:
# 位于CPU和GPU的两tensor做运算
device = 'cuda:0' if torch.cuda.is_available() else 'cpu'
print(device)

x = torch.rand(2,2,device=device)
y = torch.rand(2,2)
x + y.to(device)

cuda:0


tensor([[1.1296, 0.4521],
        [1.0114, 0.3211]], device='cuda:0')

In [10]:
# 两个shape不同的tensor做运算
x = torch.rand(2,2)
y = torch.rand(3,3)
x + y

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1

In [11]:
# tensor重要的属性：dtype, device, shape
device = 'cuda:0' if torch.cuda.is_available() else 'cpu'
print(device)

x = torch.rand(2,2,device=device)
print(x.dtype)
print(x.device)
print(x.shape)

cuda:0
torch.float32
cuda:0
torch.Size([2, 2])


# 3. tensor的运算

In [12]:
# indexing（索引）与slicing（切片）
tensor = torch.ones(4, 4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [13]:
# 堆叠tensor
tensor = torch.ones(2, 3)
tensor_cat = torch.cat([tensor, tensor, tensor], dim=1)
tensor_cat

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [14]:
# 两个tensor加减（维度相同）
x1 = torch.ones(3,3)
x2 = torch.ones(3,3)
x1 + x2

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [15]:
# 两个tensor加减（维度不同，属于特殊情况）
x1 = torch.ones(1,3)
x2 = torch.rand(3,3)
x1 + x2

tensor([[1.1656, 1.2699, 1.7637],
        [1.4880, 1.9893, 1.6926],
        [1.9923, 1.9103, 1.5053]])

In [16]:
# 两个tensor相乘（element-wise）
x1 = torch.ones(2, 3)
x2 = torch.rand(2, 3)

print(x2)
x1 * x2

tensor([[0.0950, 0.1850, 0.7992],
        [0.4596, 0.4764, 0.7313]])


tensor([[0.0950, 0.1850, 0.7992],
        [0.4596, 0.4764, 0.7313]])

In [17]:
# 两个tensor相乘（matrix multiplication）
x1 = torch.ones(2, 3)
x2 = torch.rand(2, 3)

print('x2: ', x2, '\n')
print(x1.t().matmul(x2))
print(x1.t() @ x2)

x2:  tensor([[0.6370, 0.9080, 0.1730],
        [0.6288, 0.2830, 0.5226]]) 

tensor([[1.2658, 1.1911, 0.6957],
        [1.2658, 1.1911, 0.6957],
        [1.2658, 1.1911, 0.6957]])
tensor([[1.2658, 1.1911, 0.6957],
        [1.2658, 1.1911, 0.6957],
        [1.2658, 1.1911, 0.6957]])
